added Omit to the types import list
i'm using typescript 3.4.5., where `Omit` is not included as part of TS,  and i get the following error: 

```
 ../../node_modules/react-use-gesture/dist/hooks.d.ts:16:45 - error TS2304: Cannot find name 'Omit'.
[1] 16 declare type PartialGestureConfig = Partial<Omit<GestureConfig, 'passiveEvents'>>;
```

since this project already defined and exported a type helper for `Omit`, importing it should fix this.